# Generated by Django 4.1 on 2022-09-22 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0002_city_drinking_education_gender_instagram_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='zodiac_sign',
        ),
        migrations.AddField(
            model_name='user',
            name='zodiac_sign',
            field=models.ManyToManyField(default=None, to='api_app.zodiacsign'),
        ),
    ]
