# Generated by Django 4.1 on 2022-10-03 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0004_remove_zodiacsign_lang_remove_user_city_of_origin_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drinking',
            name='lang',
        ),
        migrations.RemoveField(
            model_name='education',
            name='lang',
        ),
        migrations.RemoveField(
            model_name='gender',
            name='lang',
        ),
        migrations.RemoveField(
            model_name='interestcategory',
            name='name',
        ),
        migrations.RemoveField(
            model_name='kids',
            name='lang',
        ),
        migrations.RemoveField(
            model_name='lookingfor',
            name='lang',
        ),
        migrations.RemoveField(
            model_name='politicalview',
            name='lang',
        ),
        migrations.RemoveField(
            model_name='religion',
            name='lang',
        ),
        migrations.RemoveField(
            model_name='smoking',
            name='lang',
        ),
        migrations.RemoveField(
            model_name='workout',
            name='lang',
        ),
        migrations.AddField(
            model_name='gender',
            name='show',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='drinking',
            name='name',
            field=models.CharField(choices=[('Compañia', 'Sólo en compañía'), ('Nunca', 'Nunca'), ('Con frecuencia', 'Con frecuencia'), ('No bebo', 'No bebo')], max_length=16),
        ),
        migrations.AlterField(
            model_name='education',
            name='name',
            field=models.CharField(choices=[('Preparatoria', 'Preparatoria'), ('Formación profesional', 'Formación profesional'), ('Estudiando una licenciatura', 'Estudiando una licenciatura'), ('Bachillerato', 'Bachillerato'), ('Estudiando un posgrado', 'Estudiando un posgrado'), ('Posgrado', 'Posgrado')], max_length=27),
        ),
        migrations.AlterField(
            model_name='gender',
            name='name',
            field=models.CharField(choices=[('Mujer', 'Mujer'), ('Hombre', 'Hombre'), ('No binario', 'No binario'), ('Otro', 'Otro')], max_length=10),
        ),
        migrations.AlterField(
            model_name='interestcategory',
            name='lang',
            field=models.CharField(choices=[('Creatividad', 'Creatividad'), ('Deportes', 'Deportes'), ('Salidas', 'Salidas'), ('Quedarse en casa', 'Quedarse en casa'), ('Cine y televisión', 'Cine y televisión'), ('Leer', 'Leer'), ('Música', 'Música'), ('Comida y bebida', 'Comida y bebida'), ('Viajes', 'Viajes'), ('Mascotas', 'Mascotas'), ('Valores y personalidad', 'Valores y personalidad'), ('Causas', 'Causas')], max_length=25),
        ),
        migrations.AlterField(
            model_name='kids',
            name='name',
            field=models.CharField(choices=[('Algún día', 'Algún día'), ('No quiero', 'No quiero'), ('Ya tengo y quiero mas', 'Ya tengo y quiero mas'), ('Ya tengo y no quiero mas', 'Ya tengo y no quiero mas'), ('Aún no se', 'Aún no se')], max_length=25),
        ),
        migrations.AlterField(
            model_name='lookingfor',
            name='name',
            field=models.CharField(choices=[('Relación', 'Relación'), ('Nada serio', 'Nada serio'), ('No lo se aún', 'No lo se aún'), ('Matrimonio', 'Matrimonio')], max_length=12),
        ),
        migrations.AlterField(
            model_name='politicalview',
            name='name',
            field=models.CharField(choices=[('Sin interés', 'Sin interés'), ('De centro', 'De centro'), ('Izquierda', 'Izquierda'), ('Derecha', 'Derecha'), ('Socialista', 'Socialista')], max_length=11),
        ),
        migrations.AlterField(
            model_name='religion',
            name='name',
            field=models.CharField(choices=[('Agnosticismo', 'Agnosticismo'), ('Ateísmo', 'Ateísmo'), ('Budismo', 'Budismo'), ('Catolicismo', 'Catolicismo'), ('Cristianismo', 'Cristianismo'), ('Hinduismo', 'Hinduismo'), ('Judaismo', 'Judaismo'), ('Jainismo', 'Jainismo'), ('Mormonismo', 'Mormonismo'), ('Islam', 'Islam'), ('Zoroastrismo', 'Zoroastrismo'), ('Sijismo', 'Sijismo'), ('Espiritual', 'Espiritual'), ('Otra', 'Otra')], max_length=12),
        ),
        migrations.AlterField(
            model_name='smoking',
            name='name',
            field=models.CharField(choices=[('Sólo en compañía', 'Sólo en compañía'), ('Nunca', 'Nunca'), ('Habitualmente', 'Habitualmente')], max_length=16),
        ),
        migrations.AlterField(
            model_name='workout',
            name='name',
            field=models.CharField(choices=[('A menudo', 'A menudo'), ('A veces', 'A veces'), ('Casi nunca', 'Casi nunca')], max_length=10),
        ),
    ]
