# Generated by Django 4.1 on 2022-10-09 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0005_remove_drinking_lang_remove_education_lang_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='drinking',
        ),
        migrations.RemoveField(
            model_name='user',
            name='education',
        ),
        migrations.RemoveField(
            model_name='user',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='user',
            name='kids',
        ),
        migrations.RemoveField(
            model_name='user',
            name='looking_for',
        ),
        migrations.RemoveField(
            model_name='user',
            name='political_views',
        ),
        migrations.RemoveField(
            model_name='user',
            name='religion',
        ),
        migrations.RemoveField(
            model_name='user',
            name='smoking',
        ),
        migrations.RemoveField(
            model_name='user',
            name='workout',
        ),
        migrations.RemoveField(
            model_name='user',
            name='zodiac_sign',
        ),
        migrations.DeleteModel(
            name='Drinking',
        ),
        migrations.DeleteModel(
            name='Education',
        ),
        migrations.DeleteModel(
            name='Gender',
        ),
        migrations.DeleteModel(
            name='Kids',
        ),
        migrations.DeleteModel(
            name='LookingFor',
        ),
        migrations.DeleteModel(
            name='PoliticalView',
        ),
        migrations.DeleteModel(
            name='Religion',
        ),
        migrations.DeleteModel(
            name='Smoking',
        ),
        migrations.DeleteModel(
            name='Workout',
        ),
        migrations.DeleteModel(
            name='ZodiacSign',
        ),
        migrations.AddField(
            model_name='user',
            name='drinking',
            field=models.CharField(choices=[('Compañia', 'Sólo en compañía'), ('Nunca', 'Nunca'), ('Con frecuencia', 'Con frecuencia'), ('No bebo', 'No bebo')], default=None, max_length=16),
        ),
        migrations.AddField(
            model_name='user',
            name='education',
            field=models.CharField(choices=[('Preparatoria', 'Preparatoria'), ('Formación profesional', 'Formación profesional'), ('Estudiando una licenciatura', 'Estudiando una licenciatura'), ('Bachillerato', 'Bachillerato'), ('Estudiando un posgrado', 'Estudiando un posgrado'), ('Posgrado', 'Posgrado')], default=None, max_length=27),
        ),
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('Mujer', 'Mujer'), ('Hombre', 'Hombre'), ('No binario', 'No binario'), ('Otro', 'Otro')], default=None, max_length=10),
        ),
        migrations.AddField(
            model_name='user',
            name='kids',
            field=models.CharField(choices=[('Algún día', 'Algún día'), ('No quiero', 'No quiero'), ('Ya tengo y quiero mas', 'Ya tengo y quiero mas'), ('Ya tengo y no quiero mas', 'Ya tengo y no quiero mas'), ('Aún no se', 'Aún no se')], default=None, max_length=25),
        ),
        migrations.AddField(
            model_name='user',
            name='looking_for',
            field=models.CharField(choices=[('Relación', 'Relación'), ('Nada serio', 'Nada serio'), ('No lo se aún', 'No lo se aún'), ('Matrimonio', 'Matrimonio')], default=None, max_length=12),
        ),
        migrations.AddField(
            model_name='user',
            name='political_views',
            field=models.CharField(choices=[('Sin interés', 'Sin interés'), ('De centro', 'De centro'), ('Izquierda', 'Izquierda'), ('Derecha', 'Derecha'), ('Socialista', 'Socialista')], default=None, max_length=11),
        ),
        migrations.AddField(
            model_name='user',
            name='religion',
            field=models.CharField(choices=[('Agnosticismo', 'Agnosticismo'), ('Ateísmo', 'Ateísmo'), ('Budismo', 'Budismo'), ('Catolicismo', 'Catolicismo'), ('Cristianismo', 'Cristianismo'), ('Hinduismo', 'Hinduismo'), ('Judaismo', 'Judaismo'), ('Jainismo', 'Jainismo'), ('Mormonismo', 'Mormonismo'), ('Islam', 'Islam'), ('Zoroastrismo', 'Zoroastrismo'), ('Sijismo', 'Sijismo'), ('Espiritual', 'Espiritual'), ('Otra', 'Otra')], default=None, max_length=12),
        ),
        migrations.AddField(
            model_name='user',
            name='smoking',
            field=models.CharField(choices=[('Sólo en compañía', 'Sólo en compañía'), ('Nunca', 'Nunca'), ('Habitualmente', 'Habitualmente')], default=None, max_length=16),
        ),
        migrations.AddField(
            model_name='user',
            name='workout',
            field=models.CharField(choices=[('A menudo', 'A menudo'), ('A veces', 'A veces'), ('Casi nunca', 'Casi nunca')], default=None, max_length=10),
        ),
        migrations.AddField(
            model_name='user',
            name='zodiac_sign',
            field=models.CharField(choices=[('Aries', 'Aries'), ('Tauro', 'Taurus'), ('Geminis', 'Gemini'), ('Cancer', 'Cancer'), ('Leo', 'Leo'), ('Virgo', 'Virgo'), ('Libra', 'Libra'), ('Escorpio', 'Escorpio'), ('Sagitario', 'Sagitario'), ('Capricornio', 'Capricornio'), ('Acuario', 'Acuario'), ('Piscis', 'Piscis')], default=None, max_length=11),
        ),
    ]
